Repository ethereum/staking-launchpad, pull requests merged in 2020-12, with the labels that each got.

#283 adjusts network order so portis connects to mainnet by default
  src/pages/ConnectWallet/web3Utils.ts
Labels: bug

#287 master -> mainnet
  .env.medalla
  .env.pyrmont
  .env.template
  src/pages/ConnectWallet/web3Utils.ts
  src/pages/Landing/TimelineMilestones.tsx
  src/utils/envVars.ts
  src/utils/queryContract.ts
Labels: release

#288 duplicate your
  src/pages/GenerateKeys/index.tsx
Labels: bug, content

#280 Allow retry on failed deposits
  src/pages/Transactions/Keylist/ActionButton.tsx
  src/pages/Transactions/transactionUtils.tsx
Labels: bug
