Repository ethereum/staking-launchpad, pull requests merged in 2020-09, with the labels that each got.

#167 improves multi-tx UX: wait for tx confirmation before requesting the next
  src/pages/GenerateKeys/Option1.tsx
  src/pages/GenerateKeys/Option2.tsx
  src/pages/Transactions/Keylist/index.tsx
  src/pages/Transactions/index.tsx
  src/pages/Transactions/transactionUtils.tsx
Labels: bug, enhancement

#175 Update FAQ (index.jsx)
  src/pages/FAQ/index.jsx
Labels: content, enhancement

#173 select validator updates
  src/components/ImageSelectionBox.tsx
  src/components/WorkflowPage/EthRoundLogo.tsx
  src/components/WorkflowPage/WorkflowProgressBar.tsx
  src/pages/GenerateKeys/OperatingSystemButtons.tsx
  src/pages/SelectValidator/SelectValidatorButtons.tsx
  src/pages/SelectValidator/SelectValidatorSection.tsx
  src/pages/SelectValidator/index.tsx
  src/pages/ValidatorClients/Lighthouse.tsx
  src/pages/ValidatorClients/Nimbus.tsx
  src/pages/ValidatorClients/Prysm.tsx
  src/pages/ValidatorClients/Teku.tsx
  src/static/gethereum-mascot-circle.png
  src/static/hyperledger-besu-circle.png
  src/static/lighthouse-circle.png
  src/static/nethermind-circle.png
  src/static/nimbus-circle.png
  src/static/parity-circle.png
  src/static/pegasys-teku-circle.png
  src/static/prysmatic-labs-circle.png
  src/store/actions/index.ts
  src/store/actions/validatorActions.ts
  src/store/reducers/index.ts
  src/store/reducers/validatorReducer.ts
  src/store/reducers/workflowReducer.ts
  src/styles/GlobalStyles.ts
Labels: enhancement

#174 Eth1 Content
  src/Routes.tsx
  src/components/WorkflowPage/WorkflowPageTemplate.tsx
  src/components/WorkflowPage/WorkflowProgressBar.tsx
  src/pages/Acknowledgements/AcknowledgementSection.tsx
  src/pages/Acknowledgements/index.tsx
  src/pages/Clients/Eth1/Besu.tsx
  src/pages/Clients/Eth1/Geth.tsx
  src/pages/Clients/Eth1/Nethermind.tsx
  src/pages/Clients/Eth1/OpenEthereum.tsx
  src/pages/Clients/Eth2/Lighthouse.tsx
  src/pages/Clients/Eth2/Nimbus.tsx
  src/pages/Clients/Eth2/Prysm.tsx
  src/pages/Clients/Eth2/Teku.tsx
  src/pages/Clients/ValidatorClientComponents.tsx
  src/pages/GenerateKeys/index.tsx
  src/pages/SelectClient/SelectClientButtons.tsx
  src/pages/SelectClient/SelectClientSection.tsx
  src/pages/SelectClient/index.tsx
  src/pages/SelectValidator/index.tsx
  src/pages/ValidatorClients/Lighthouse.tsx
  src/pages/index.ts
  src/store/actions/clientActions.ts
  src/store/actions/index.ts
  src/store/actions/validatorActions.ts
  src/store/actions/workflowActions.ts
  src/store/reducers/clientReducer.ts
  src/store/reducers/index.ts
  src/store/reducers/validatorReducer.ts
  src/utils/RouteToCorrectWorkflowStep.tsx
Labels: enhancement

#176 Update Hero.tsx (change payouts to rewards)
  src/pages/Landing/Hero.tsx
Labels: bug, content

#180 GENESIS_FORK_VERSION as bytes
  src/pages/FAQ/index.jsx
  src/pages/UploadValidator/index.tsx
  src/utils/envVars.ts
Labels: bug

#172 Add "Select Validator" step to workflow
  src/Routes.tsx
  src/components/ImageSelectionBox.tsx
  src/components/WorkflowPage/EthRoundLogo.tsx
  src/components/WorkflowPage/WorkflowPageTemplate.tsx
  src/components/WorkflowPage/WorkflowProgressBar.tsx
  src/pages/Acknowledgements/AcknowledgementSection.tsx
  src/pages/Acknowledgements/index.tsx
  src/pages/Clients/Eth1/Besu.tsx
  src/pages/Clients/Eth1/Geth.tsx
  src/pages/Clients/Eth1/Nethermind.tsx
  src/pages/Clients/Eth1/OpenEthereum.tsx
  src/pages/Clients/Eth2/Lighthouse.tsx
  src/pages/Clients/Eth2/Nimbus.tsx
  src/pages/Clients/Eth2/Prysm.tsx
  src/pages/Clients/Eth2/Teku.tsx
  src/pages/Clients/ValidatorClientComponents.tsx
  src/pages/GenerateKeys/OperatingSystemButtons.tsx
  src/pages/GenerateKeys/index.tsx
  src/pages/SelectClient/SelectClientButtons.tsx
  src/pages/SelectClient/SelectClientSection.tsx
  src/pages/SelectClient/index.tsx
  src/pages/ValidatorClients/Nimbus.tsx
  src/pages/ValidatorClients/Prysm.tsx
  src/pages/index.ts
  src/static/gethereum-mascot-circle.png
  src/static/hyperledger-besu-circle.png
  src/static/lighthouse-circle.png
  src/static/nethermind-circle.png
  src/static/nimbus-circle.png
  src/static/parity-circle.png
  src/static/pegasys-teku-circle.png
  src/static/prysmatic-labs-circle.png
  src/store/actions/clientActions.ts
  src/store/actions/index.ts
  src/store/actions/workflowActions.ts
  src/store/reducers/clientReducer.ts
  src/store/reducers/index.ts
  src/styles/GlobalStyles.ts
  src/utils/RouteToCorrectWorkflowStep.tsx
Labels: enhancement

#184 [Urgent] Update TX status to PENDING in `handleMultipleTransactions`
  src/pages/Transactions/Keylist/ActionButton.tsx
  src/pages/Transactions/index.tsx
  src/pages/Transactions/transactionUtils.tsx
Labels: bug
