Repository ethereum/staking-launchpad, pull requests merged in 2020-07, with the labels that each got.

#89 Page template for new non-workflow pages
  src/components/PageTemplate.tsx
Labels: do not merge

#105 Tomo's UI tweaks
  src/components/Button.tsx
  src/components/Link.tsx
  src/components/WorkflowPage/WorkflowPageTemplate.tsx
  src/pages/Acknowledgements/AcknowledgementProgressTracker/AcknowledgementProgressStep.tsx
  src/pages/Acknowledgements/pageContent.tsx
  src/pages/Summary/index.tsx
  src/static/eth-round-landing.svg
  src/styles/styledComponentsTheme.ts
Labels: aesthetics

#101 Adds client cards on congrats page
  package.json
  src/pages/Congratulations/ClientCard.tsx
  src/pages/Congratulations/ProgressBarInfo.tsx
  src/pages/Congratulations/index.tsx
  src/static/lighthouse-bg.png
  src/static/nimbus-bg.png
  src/static/prysmatic-bg.png
  src/static/teku-bg.png
  yarn.lock
Labels: aesthetics, content, enhancement

#98 adds placeholder ledger button
  src/pages/ConnectWallet/WalletButton.tsx
  src/pages/ConnectWallet/index.tsx
  src/static/ledger-thumbnail.png
Labels: enhancement

#103 Insert rhino mascot on landing page and as favicon
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/apple-touch-icon.png
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/index.html
  src/pages/Landing/Hero.tsx
  src/static/eth2-leslie-rhino.png
Labels: aesthetics

#93 Testnet clarification
  public/index.html
  src/components/AppBar.tsx
  src/pages/Acknowledgements/pageContent.tsx
  src/pages/Congratulations/ProgressBarInfo.tsx
  src/pages/ConnectWallet/index.tsx
  src/pages/GenerateKeys/index.tsx
  src/pages/Landing/Hero.tsx
  src/pages/Landing/NetworkStatus/index.tsx
  src/pages/Landing/SignupSteps/index.tsx
  src/pages/Landing/StakingRewards.tsx
  src/pages/Landing/StakingRewardsChart/index.tsx
  src/pages/Landing/StakingRewardsChart/scene/StakingRewardsChartTooltip.tsx
  src/pages/Summary/index.tsx
  src/utils/envVars.ts
Labels: aesthetics, content

#102 add validator FAQ link to landing page
  src/pages/Congratulations/index.tsx
  src/pages/Landing/Phases/PhaseCard.tsx
  src/pages/Landing/Phases/index.tsx
Labels: content

#109 Remove broken links & add phishing explainer page
  src/Routes.tsx
  src/components/Link.tsx
  src/pages/Acknowledgements/pageContent.tsx
  src/pages/Landing/Phases/index.tsx
  src/pages/Phishing/index.tsx
  src/pages/Summary/index.tsx
  src/pages/index.ts
Labels: content, enhancement

#100 Progress bar after Genesis threshold
  src/pages/Landing/NetworkStatus/index.tsx
  src/styles/GlobalStyles.ts
Labels: aesthetics, bug

#107 Add client pages
  src/Routes.tsx
  src/pages/Congratulations/ClientCard.tsx
  src/pages/Congratulations/index.tsx
  src/pages/ValidatorClients/Lighthouse.tsx
  src/pages/ValidatorClients/Nimbus.tsx
  src/pages/ValidatorClients/Prysm.tsx
  src/pages/ValidatorClients/Teku.tsx
  src/pages/ValidatorClients/ValidatorClientComponents.tsx
Labels: content, enhancement

#120 Remove all references to "eth1"
  src/pages/Acknowledgements/pageContent.tsx
  src/pages/FAQ/index.jsx
  src/pages/Landing/Introduction.tsx
  src/pages/Phishing/index.tsx
Labels: content

#108 Differentiate between invalid deposit file and bad deposit data
  src/pages/UploadValidator/index.tsx
Labels: enhancement

#125 Clarifies numbers on network status
  src/pages/Landing/NetworkStatus/index.tsx
Labels: content
