Repository ethereum/staking-launchpad, pull requests merged in 2021-03, with the labels that each got.

#377 Fix links to beaconcha.in validator page
  src/pages/TopUp/components/ValidatorTable.tsx
  src/pages/Transactions/Keylist/ActionButton.tsx
Labels: bug

#382 dev -> master (Pyrmont release)
  public/index.html
  src/Routes.tsx
  src/components/PageTemplate.tsx
  src/components/WorkflowPage/WorkflowPageTemplate.tsx
  src/intl/compiled/en.json
  src/intl/en.json
Labels: release

#386 Adds Prater Testnet suport
  .env.mainnet
  .env.prater
  .env.template
Labels: enhancement, release

#390 dev -> master (Testnets release)
  .env.mainnet
  .env.prater
  .env.template
  src/components/AppBar.tsx
  src/components/LocalizedRouter.tsx
  src/intl/compiled/ar.json
  src/intl/compiled/el.json
  src/intl/compiled/en.json
  src/intl/compiled/fr.json
  src/intl/compiled/id.json
  src/intl/compiled/it.json
  src/intl/compiled/ja.json
  src/intl/compiled/ko.json
  src/intl/compiled/pt-br.json
  src/intl/compiled/ro.json
  src/intl/compiled/zh.json
  src/intl/en.json
  src/intl/index.ts
  src/pages/Acknowledgements/AcknowledgementProgressTracker/index.tsx
  src/pages/Checklist/index.tsx
  src/pages/Languages/index.tsx
  src/static/github-cli-screenshot.png
Labels: release
